// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDneliIMXhe5n0CIlQ4tRT1A5ARISfJmec',
    appId: '1:1034631470177:web:7eedda176c14b9e4f95e20',
    messagingSenderId: '1034631470177',
    projectId: 'ride-b0372',
    authDomain: 'ride-b0372.firebaseapp.com',
    storageBucket: 'ride-b0372.appspot.com',
    measurementId: 'G-0GTJWEFMR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSx4ag3Cn04U1pTOmDIjv4qgzXZ8Y6HMI',
    appId: '1:1034631470177:android:59db78eed294bd54f95e20',
    messagingSenderId: '1034631470177',
    projectId: 'ride-b0372',
    storageBucket: 'ride-b0372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlxVMmnFoPyKnGSXkTBCbRftOnvox65G8',
    appId: '1:1034631470177:ios:c9ae15cb2a934aacf95e20',
    messagingSenderId: '1034631470177',
    projectId: 'ride-b0372',
    storageBucket: 'ride-b0372.appspot.com',
    iosClientId: '1034631470177-gp2128o9bcrr09r1vjlv9jqvp3uon4v5.apps.googleusercontent.com',
    iosBundleId: 'com.ride.rideusuario.rideUsuario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlxVMmnFoPyKnGSXkTBCbRftOnvox65G8',
    appId: '1:1034631470177:ios:c9ae15cb2a934aacf95e20',
    messagingSenderId: '1034631470177',
    projectId: 'ride-b0372',
    storageBucket: 'ride-b0372.appspot.com',
    iosClientId: '1034631470177-gp2128o9bcrr09r1vjlv9jqvp3uon4v5.apps.googleusercontent.com',
    iosBundleId: 'com.ride.rideusuario.rideUsuario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDneliIMXhe5n0CIlQ4tRT1A5ARISfJmec',
    appId: '1:1034631470177:web:41093c8ecebc91fef95e20',
    messagingSenderId: '1034631470177',
    projectId: 'ride-b0372',
    authDomain: 'ride-b0372.firebaseapp.com',
    storageBucket: 'ride-b0372.appspot.com',
    measurementId: 'G-S108R2KKW6',
  );

}